import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Button from '@/components/Button'
import Form from '@/components/Form'
import FaceBookButton from '@/components/FaceBookButton'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/instagram.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.login}>
            <img className={styles.textLogo} src="https://1000logos.net/wp-content/uploads/2017/02/Logo-Instagram.png" alt="Instgram Logo"></img>
              <div className={styles.formField}>
              <Form></Form>
              </div>
              <Button></Button>
              <div className={styles.lineBreak}>
              <hr width="100%"/><span className={styles.lineBreakText}>OR</span><hr width="100%"/>
              </div>
              <FaceBookButton></FaceBookButton>
              <span className={styles.password}>Forgot password?</span>
        </div>
      </main>
    </>
  )
}
